name: 🔨 Build and Push Docker Image

on:
  pull_request:
  push:
    branches: [development]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image"
        type: string
        required: true
  workflow_call:
    inputs:
      tag:
        description: "Tag for the Docker image"
        type: string
        required: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  dev:
    needs: test
    if: github.ref == 'refs/heads/development'
    uses: equinor/ops-actions/.github/workflows/docker.yml@e925ef9959a37d43073b77efa2f73c64253fbd55 # v9.37.2
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      environment: dev
      registry: registry.hub.docker.com
      username: sondresjo
      repository: sondresjo/garge-operator
      tag: dev

  prod:
    needs: test
    if: inputs.tag != ''
    uses: equinor/ops-actions/.github/workflows/docker.yml@e925ef9959a37d43073b77efa2f73c64253fbd55 # v9.37.2
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      environment: prod
      registry: registry.hub.docker.com
      username: sondresjo
      repository: sondresjo/garge-operator
      tag: ${{ github.event.release.tag_name || inputs.tag }}
