name: 🚀 Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to update changelog file
  pull-requests: write # Required to create release PRs
  issues: write

jobs:
  release-please:
    name: Release Please
    uses: equinor/ops-actions/.github/workflows/release-please.yml@6f3c4901194b286f11800f60fc034417e2c8480a # v9.36.0
    with:
      release_type: simple
