name: 🚀 Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to update changelog file
  pull-requests: write # Required to create release PRs
  issues: write

jobs:
  release-please:
    name: Release Please
    uses: equinor/ops-actions/.github/workflows/release-please.yml@39749d0c32762076499120f881e963687374420c # v9.37.1
    with:
      release_type: simple
